[package]
name = "corroded_drone"
version = "0.1.0"
authors = ["Matous Hybl <hyblmatous@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
env_logger = "0.7.0"
chrono = "0.4"
